# Part 1: Theory, Implementation and Visualization

In [ ]:
import sys
import os
import numpy as np

sys.path.append(os.path.abspath(".."))
from part1.ols_implementation import hat_matrix

# Tạo dữ liệu giả lập (3 mẫu, 2 đặc trưng)
X_test = np.array([[1, 2], [1, 3], [1, 5]])

H = hat_matrix(X_test)

H_squared = H @ H
assert np.allclose(H_squared, H), "Lỗi: Ma trận Hat không có tính lũy đẳng!"
print("Xác nhận: H^2 == H. Task hoàn tất!")

Ma trận Hat H:
[[ 0.7143  0.4286 -0.1429]
 [ 0.4286  0.3571  0.2143]
 [-0.1429  0.2143  0.9286]]

Kiểm tra H^2 == H: True


In [3]:
import sys
import os
import numpy as np

# 1. Khai báo thư mục cha để Jupyter nhận diện được module 'part1'
if os.path.abspath("..") not in sys.path:
    sys.path.append(os.path.abspath(".."))

from part1.ols_implementation import ols_fit

# 2. Tạo dữ liệu giả lập (100 mẫu, 3 đặc trưng)
np.random.seed(42)
X_test_ols = np.random.rand(100, 3)
true_beta = np.array([1.5, -2.0, 3.1])
# Thêm nhiễu ngẫu nhiên vào biến mục tiêu y
y_test_ols = X_test_ols @ true_beta + np.random.randn(100) * 0.5 

# 3. Tính toán bằng hàm tự viết
beta_hat, sigma2 = ols_fit(X_test_ols, y_test_ols)

# 4. Tính toán bằng thư viện chuẩn của NumPy
beta_numpy, residuals, rank, s = np.linalg.lstsq(X_test_ols, y_test_ols, rcond=None)

# 5. Kiểm chứng (Assert)
assert np.allclose(beta_hat, beta_numpy), "Lỗi: beta_hat không khớp với numpy!"
print("✅ Xác nhận: Hàm ols_fit tính toán beta_hat chính xác, khớp 100% với numpy.linalg.lstsq!")
print(f"🔹 Beta hat (Our Implementation): {beta_hat}")
print(f"🔹 Noise Variance (sigma^2): {sigma2:.4f}")

✅ Xác nhận: Hàm ols_fit tính toán beta_hat chính xác, khớp 100% với numpy.linalg.lstsq!
🔹 Beta hat (Our Implementation): [ 1.55622667 -2.14794769  3.29602592]
🔹 Noise Variance (sigma^2): 0.2415
