# Part 1: Theory, Implementation and Visualization

In [ ]:
import sys
import os
import numpy as np

sys.path.append(os.path.abspath(".."))
from part1.ols_implementation import hat_matrix

# Tạo dữ liệu giả lập (3 mẫu, 2 đặc trưng)
X_test = np.array([[1, 2], [1, 3], [1, 5]])

H = hat_matrix(X_test)

H_squared = H @ H
assert np.allclose(H_squared, H), "Lỗi: Ma trận Hat không có tính lũy đẳng!"
print("Xác nhận: H^2 == H. Task hoàn tất!")

Ma trận Hat H:
[[ 0.7143  0.4286 -0.1429]
 [ 0.4286  0.3571  0.2143]
 [-0.1429  0.2143  0.9286]]

Kiểm tra H^2 == H: True
